#include <d3d11.h>

#pragma comment(lib, "d3d11.lib")

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_d3d11_impl_D3D11 */

        
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_d3d11_impl_D3D11_D3D11_SDK_VERSION
#define org_lwjgl_d3d11_impl_D3D11_D3D11_SDK_VERSION 7L
    /*
    * Class:     org_lwjgl_d3d11_impl_D3D11
    * Method:    D3D11CreateDeviceAndSwapChain0
    * Signature: (JIJILjava/nio/IntBuffer;ILjava/nio/ByteBuffer;Lorg/lwjgl/PointerBuffer;Lorg/lwjgl/PointerBuffer;Ljava/nio/IntBuffer;Lorg/lwjgl/PointerBuffer;)J
    */
    JNIEXPORT jlong JNICALL Java_org_lwjgl_d3d11_impl_D3D11_D3D11CreateDeviceAndSwapChain0
        (JNIEnv * env, jclass clazz, jlong adapterPtr, jint driverType, 
        jlong module, jint flags, jobject featureLevels, jint sdkVersion, 
        jobject swapChainDesc, jobject swapChainOut, jobject deviceOut, 
        jobject featureLevelOut, jobject immediateContextOut) {
        return 0L;
    }

#ifdef __cplusplus
}
#endif

namespace lwjgl {
    namespace d3d11 {

    }
}
