package org.lwjgl.d3d11;

public class DXGI_MODE_DESC {

    int Width;
    int Height;
    DXGI_RATIONAL RefreshRate = new DXGI_RATIONAL();
    DXGI_FORMAT Format = DXGI_FORMAT.DXGI_FORMAT_UNKNOWN;
    DXGI_MODE_SCANLINE_ORDER ScanlineOrdering = DXGI_MODE_SCANLINE_ORDER.DXGI_MODE_SCANLINE_ORDER_UNSPECIFIED;
    DXGI_MODE_SCALING Scaling = DXGI_MODE_SCALING.DXGI_MODE_SCALING_UNSPECIFIED;

}
