package org.lwjgl.d3d11;

public interface DXGISwapChainFlag {

    int DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1;
    int DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2;
    int DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4;
    int DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8;
    int DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16;
    int DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32;
    int DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64;
    int DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128;
    int DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256;
    int DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 512;

}
